[package]
name = "sidevm-quickjs"
version = "0.9.4"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[[bin]]
name = "sidejs"
path = "src/sidejs.rs"

[[bin]]
name = "phatjs"
path = "src/phatjs.rs"

[dependencies]
js = { package = "qjsbind", path = "qjs-sys/qjsbind" }
qjs-extensions = { path = "qjs-sys/qjs-extensions", features = ['std'] }
tokio = { version = "1", features = ["sync", "macros", "io-util"] }
hyper = { version = "0.14", features = ["client", "http1"] }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
bootcode = { path = "bootcode" }
sidevm = "0.2.0-alpha.7"
log = "0.4"
anyhow = "1.0"
url = "2.4.0"
ink_macro = "4.3"
scale = { package = "parity-scale-codec", version = "3" }
hex = "0.4.3"
pink-types = "0.1"

sha2 = { version = "0.10", optional = true, default-features = false }
sha3 = { version = "0.10", optional = true, default-features = false }
blake2 = { version = "0.10", optional = true, default-features = false }

# Crates for native testing
tracing-subscriber = { version = "0.3", optional = true }
rand = { version = "0.8.5", optional = true }
hyper-rustls = { version = "0.24.1", optional = true }

# Creates for web backend
wasm-bindgen = { version = "0.2.89", optional = true, default-features = false }
js-sys = { version = "0.3.66", optional = true }
wasm-bindgen-futures = { version = "0.4.39", optional = true }
reqwest = { version = "0.11.22", optional = true }
phala-allocator = { version = "0.1.0", optional = true }

[dependencies.web-sys]
version = "0.3.4"
optional = true
features = ['Window', 'console']

[features]
default = ["native", "js-url", "js-http-listen", "js-hash"]
sanitize-address = ["js/sanitize-address"]
js-url = []
js-http-listen = []
js-hash = ["sha2", "sha3", "blake2"]

stream = ["js/stream"]
sidevm = []
web = ["js-sys", "web-sys", "wasm-bindgen", "wasm-bindgen-futures", "reqwest"]
mem-stats = ["phala-allocator", "js/pink-allocator"]

native = [
  "tokio/full",
  "tracing-subscriber",
  "rand",
  "hyper/runtime",
  "hyper/tcp",
  "hyper-rustls/webpki-roots",
]
